const ServiceData = [
    {
        service_title: 'Frontend Developer',
        service_info: 'Frontend web Ui development in CMS. Develop more respondive Ui website',
        service_info_2: 'Develop frontend web application which is fully responsive on any device and create attractive user interface with this kind of technology.',
        service_img: 'https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/content/cover_image_file/cover_image/689192/retina_500x200_0120-Stale-while-revalidate_Data_Fetching_with_React_Hooks-Waldek_Newsletter-5222468607946967fa1b0a4525326739.png',
        service_subtxt: 'Using Technology',
        service_txt_1: 'HTML (with latest version)',
        service_txt_2: 'CSS (with Tailwind CSS)',
        service_txt_3: 'JavaScript (Including ES6)',
        service_txt_4: 'TypeScript',
        service_txt_5: 'React',
        service_txt_6: 'React Native',
        service_txt_7: 'Next Js',
    },
    {
        service_title: 'Interactive Web Design',
        service_info: 'Create attractive super cool design and develop responsive site for any device',
        service_info_2: 'Create interactive web design where uses other inbuilt software, modules or features aimed at creating an environment for a website or web application user to be actively engaged during visit or use as the case may be, thereby improving his or her user experience (UX)',
        service_img: 'https://i.ytimg.com/vi/3aOU9MbITlM/maxresdefault.jpg',
        service_subtxt: 'Using Technology',
        service_txt_1: 'CSS (with Tailwind CSS)',
        service_txt_2: 'JavaScript (Including ES6)',
        service_txt_3: 'Bootstrap',
        service_txt_4: 'Material Ui',
        service_txt_5: 'Figma',
        service_txt_6: 'ParallalX (for object animation)',
        service_txt_7: 'Graph QL',
    },
    {
        service_title: 'Integrate Payment Getway',
        service_info: 'Using user friendly payment getway with local and global banking system.',
        service_info_2: 'Integrate billing section with local and global paym,ent getway system. Unique user profile and save their history backend server',
        service_img: 'https://cdn.searchenginejournal.com/wp-content/uploads/2020/03/the-top-10-most-popular-online-payment-solutions-5e9978d564973-1280x720.png',
        service_subtxt: 'Using Technology',
        service_txt_1: 'CSS (with Tailwind CSS)',
        service_txt_2: 'JavaScript (Including ES6)',
        service_txt_3: 'Stripe',
        service_txt_4: 'SSLCommerz',
        service_txt_5: 'Mobile Banking (Bkash, Rocket, Nagad)',
        service_txt_6: 'Paypal',
    },
    {
        service_title: 'User Authentication',
        service_info: 'Secure unique user profile and integrate log in and sign up authentication system.',
        service_info_2: 'Secure user excess and create user profile in backend server. Using any kind of authentication system.',
        service_img: 'https://www.simplilearn.com/ice9/free_resources_article_thumb/The_Importance_of_User_Authentication_Methods_in_Cyber_Security.jpg',
        service_subtxt: 'Using Technology',
        service_txt_1: 'React Hook Form',
        service_txt_2: 'JavaScript (Including ES6)',
        service_txt_3: 'Reguler Expression',
        service_txt_4: 'Firebase',
        service_txt_5: 'Mongo DB',
        service_txt_6: '',
        service_txt_7: '',
    },
    {
        service_title: 'E-commerce Development',
        service_info: 'Add custom products and update backend server data using Mongo DB.',
        service_info_2: 'Add custom products and update backend server data using Mongo DB. Create unique product searching, shopping cart, user authentication, payment getway, user friendly interactive mobile responsive design.',
        service_img: 'https://www.customsoftwarelab.com/wp-content/uploads/2020/02/Ecommerce-Customization-Key-Tips-and-Takeaways.jpg',
        service_subtxt: 'Using Technology',
        service_txt_1: 'React',
        service_txt_2: 'JavaScript (Including ES6)',
        service_txt_3: 'Mongo DB',
        service_txt_4: 'Node Js',
        service_txt_5: 'Firebase',
        service_txt_6: 'Stripe [payment getway]',
        service_txt_7: 'Material Ui',
    },
    {
        service_title: 'Search Engine Optimization',
        service_info: 'Rank website on the top page result in Google. Create most powerful backlink, useful content.',
        service_info_2: 'Create user friendly content. Maintain proper backlink for increase visitor, also analysis competitors which is most important for rank google top search rsult page.',
        service_img: 'http://lebow.drexel.edu/sites/default/files/story/1533665466-seo-image.jpg',
        service_subtxt: 'Using Technology',
        service_txt_1: 'React',
        service_txt_2: 'JavaScript (Including ES6)',
        service_txt_3: 'Mongo DB',
        service_txt_4: 'Node Js',
        service_txt_5: 'Firebase',
        service_txt_6: 'Ahrefs',
        service_txt_7: 'Uber Suggest',
    }
]

export default ServiceData;